/*
 * generated by Xtext 2.36.0
 */
package miniproject2.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DslWebModule extends AbstractDslWebModule {
}
