/*
 * generated by Xtext 2.36.0
 */
package miniproject2.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDslWebModule extends DefaultWebModule {

}
